### ISSUE TITLE
permission error

### ISSUE THREAD

**Issue by krishna0306** [Kalebu/Website-blocker-python#9]
giving this error:

Traceback (most recent call last):
  File "C:\Git\main.py", line 43, in <module>
    block_websites(9, 21)
  File "C:\Git\main.py", line 31, in block_websites
    with open(default_hoster, "r+") as hostfile:
PermissionError: [Errno 13] Permission denied: 'C:\\Windows\\System32\\drivers\\etc\\hosts'

despite running form admin mode in cmd

**Comment by kakalpa** [comment]
It is fixed in the latest update
